# remap prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# remap split
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# hot reload
bind r source-file ~/.tmux.conf

# remap pane-switching
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# enable mouse control
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

